// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/interactive/events"
	"kitbook/interactive/grpc"
	"kitbook/interactive/ioc"
	"kitbook/interactive/repository"
	"kitbook/interactive/repository/cache"
	"kitbook/interactive/repository/dao"
	"kitbook/interactive/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	interactiveDao := dao.NewGORMInteractiveDao(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewArticleInteractiveRepository(interactiveDao, interactiveCache, logger)
	client := ioc.InitSaramaClient()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, client, logger)
	v := ioc.InitConsumers(interactiveReadEventConsumer)
	interactiveService := service.NewArticleInteractiveService(interactiveRepository, logger)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRpcServer(interactiveServiceServer, logger)
	app := &App{
		consumers: v,
		server:    server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitConsumers, ioc.InitSaramaClient)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewArticleInteractiveRepository, service.NewArticleInteractiveService)
