apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitbook-mysql-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data"