// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/search/grpc"
	"kitbook/search/ioc"
	"kitbook/search/repository"
	"kitbook/search/repository/dao"
	"kitbook/search/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitES()
	userDao := dao.NewElasticSearchUserDao(client)
	userSyncRepository := repository.NewUserSyncRepository(userDao)
	articleDao := dao.NewElasticSearchArticleDao(client)
	articleSyncRepository := repository.NewArticleSyncRepository(articleDao)
	syncService := service.NewSyncService(userSyncRepository, articleSyncRepository)
	syncServiceServer := grpc.NewSyncServiceServer(syncService)
	logger := ioc.InitLogger()
	server := ioc.InitGRpcServer(syncServiceServer, logger)
	app := &App{
		rpcServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitLogger, ioc.InitES)

var syncSvcSet = wire.NewSet(dao.NewElasticSearchUserDao, dao.NewElasticSearchArticleDao, repository.NewArticleSyncRepository, repository.NewUserSyncRepository, service.NewSyncService)
