// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/feed/grpc"
	"kitbook/feed/ioc"
	"kitbook/feed/repository"
	"kitbook/feed/repository/dao"
	"kitbook/feed/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	feedPullEventDao := dao.NewFeedPullEventDao(db, logger)
	feedPushEventDao := dao.NewFeedPushEventDao(db, logger)
	feedEventRepository := repository.NewFeedEventRepository(feedPullEventDao, feedPushEventDao)
	client := ioc.InitEtcd()
	followServiceClient := ioc.InitFollowClient(client)
	v := ioc.InitHandler(feedEventRepository, followServiceClient, logger)
	feedService := service.NewFeedService(v, logger)
	feedServiceServer := grpc.NewFeedServiceServer(feedService)
	server := ioc.InitGRpcServer(feedServiceServer, logger)
	app := &App{
		rpcServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcd, ioc.InitFollowClient, ioc.InitHandler)

var feedSvcSet = wire.NewSet(dao.NewFeedPushEventDao, dao.NewFeedPullEventDao, repository.NewFeedEventRepository, service.NewFeedService)
