// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	repository2 "kitbook/interactive/repository"
	cache2 "kitbook/interactive/repository/cache"
	dao2 "kitbook/interactive/repository/dao"
	service2 "kitbook/interactive/service"
	"kitbook/internal/events/article"
	"kitbook/internal/repository"
	"kitbook/internal/repository/cache"
	"kitbook/internal/repository/dao"
	"kitbook/internal/service"
	"kitbook/internal/web"
	"kitbook/internal/web/jwt"
	"kitbook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	limiter := ioc.InitLimiter(cmdable)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	logger := InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, limiter, jwtHandler, logger)
	db := InitDB()
	userDao := dao.NewGormUserDao(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCacheUserRepository(userDao, userCache)
	userService := service.NewNormalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewcodeRepository(codeCache)
	smsService := ioc.InitSmsService(limiter)
	codeService := service.NewPhoneCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, jwtHandler, logger)
	wechatService := InitWechatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, jwtHandler, logger)
	articleDao := dao.NewGormArticleDao(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewCacheArticleRepository(articleDao, articleCache, userRepository)
	client := InitSaramaClient()
	syncProducer := InitSyncProducer(client)
	producer := article.NewSaramaSyncProducer(syncProducer)
	articleService := service.NewNormalArticleService(articleRepository, producer, logger)
	interactiveDao := dao2.NewGORMInteractiveDao(db)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewArticleInteractiveRepository(interactiveDao, interactiveCache, logger)
	interactiveService := service2.NewArticleInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

func NewArticleHandler(dao3 dao.ArticleDao) *web.ArticleHandler {
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	db := InitDB()
	userDao := dao.NewGormUserDao(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCacheUserRepository(userDao, userCache)
	articleRepository := repository.NewCacheArticleRepository(dao3, articleCache, userRepository)
	client := InitSaramaClient()
	syncProducer := InitSyncProducer(client)
	producer := article.NewSaramaSyncProducer(syncProducer)
	logger := InitLogger()
	articleService := service.NewNormalArticleService(articleRepository, producer, logger)
	interactiveDao := dao2.NewGORMInteractiveDao(db)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewArticleInteractiveRepository(interactiveDao, interactiveCache, logger)
	interactiveService := service2.NewArticleInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	return articleHandler
}

func NewInteractiveService() service2.InteractiveService {
	db := InitDB()
	interactiveDao := dao2.NewGORMInteractiveDao(db)
	cmdable := InitRedis()
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	logger := InitLogger()
	interactiveRepository := repository2.NewArticleInteractiveRepository(interactiveDao, interactiveCache, logger)
	interactiveService := service2.NewArticleInteractiveService(interactiveRepository, logger)
	return interactiveService
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
	InitSaramaClient,
	InitSyncProducer,
	InitConsumers,
)

var interactiveSvcSet = wire.NewSet(dao2.NewGORMInteractiveDao, cache2.NewRedisInteractiveCache, repository2.NewArticleInteractiveRepository, service2.NewArticleInteractiveService)

var userSvcProvider = wire.NewSet(dao.NewGormUserDao, cache.NewRedisUserCache, repository.NewCacheUserRepository, service.NewNormalUserService)
