// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/account/grpc"
	"kitbook/account/ioc"
	"kitbook/account/repository"
	"kitbook/account/repository/dao"
	"kitbook/account/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	accountDao := dao.NewGormAccountDao(db)
	accountRepository := repository.NewCacheAccountRepository(accountDao)
	accountService := service.NewaccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	server := ioc.InitGRpcServer(accountServiceServer, logger)
	app := &App{
		rpcServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger)

var paymentSvcSet = wire.NewSet(dao.NewGormAccountDao, repository.NewCacheAccountRepository, service.NewaccountService)
