// Code generated by MockGen. DO NOT EDIT.
// Source: D:./internal/repository/dao/article_es.go
//
// Generated by this command:
//
//	mockgen.exe -source=D:./internal/repository/dao/article_es.go -package=daomocks -destination=./internal/repository/dao/mocks/article.mock.go
//
// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	dao "kitbook/internal/repository/dao"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockArticleDao is a mock of ArticleDao interface.
type MockArticleDao struct {
	ctrl     *gomock.Controller
	recorder *MockArticleDaoMockRecorder
}

// MockArticleDaoMockRecorder is the mock recorder for MockArticleDao.
type MockArticleDaoMockRecorder struct {
	mock *MockArticleDao
}

// NewMockArticleDao creates a new mock instance.
func NewMockArticleDao(ctrl *gomock.Controller) *MockArticleDao {
	mock := &MockArticleDao{ctrl: ctrl}
	mock.recorder = &MockArticleDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleDao) EXPECT() *MockArticleDaoMockRecorder {
	return m.recorder
}

// GetByAuthor mocks base method.
func (m *MockArticleDao) GetByAuthor(ctx context.Context, userId int64, offset, limit int) ([]dao.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuthor", ctx, userId, offset, limit)
	ret0, _ := ret[0].([]dao.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAuthor indicates an expected call of GetByAuthor.
func (mr *MockArticleDaoMockRecorder) GetByAuthor(ctx, userId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuthor", reflect.TypeOf((*MockArticleDao)(nil).GetByAuthor), ctx, userId, offset, limit)
}

// GetById mocks base method.
func (m *MockArticleDao) GetById(ctx context.Context, artId int64) (dao.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, artId)
	ret0, _ := ret[0].(dao.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockArticleDaoMockRecorder) GetById(ctx, artId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockArticleDao)(nil).GetById), ctx, artId)
}

// GetPubById mocks base method.
func (m *MockArticleDao) GetPubById(ctx context.Context, artId int64) (dao.PublishedArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPubById", ctx, artId)
	ret0, _ := ret[0].(dao.PublishedArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPubById indicates an expected call of GetPubById.
func (mr *MockArticleDaoMockRecorder) GetPubById(ctx, artId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPubById", reflect.TypeOf((*MockArticleDao)(nil).GetPubById), ctx, artId)
}

// Insert mocks base method.
func (m *MockArticleDao) Insert(ctx context.Context, art dao.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, art)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockArticleDaoMockRecorder) Insert(ctx, art any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockArticleDao)(nil).Insert), ctx, art)
}

// ListPub mocks base method.
func (m *MockArticleDao) ListPub(ctx context.Context, start time.Time, offset, limit int) ([]dao.PublishedArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPub", ctx, start, offset, limit)
	ret0, _ := ret[0].([]dao.PublishedArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPub indicates an expected call of ListPub.
func (mr *MockArticleDaoMockRecorder) ListPub(ctx, start, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPub", reflect.TypeOf((*MockArticleDao)(nil).ListPub), ctx, start, offset, limit)
}

// Sync mocks base method.
func (m *MockArticleDao) Sync(ctx context.Context, art dao.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, art)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockArticleDaoMockRecorder) Sync(ctx, art any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockArticleDao)(nil).Sync), ctx, art)
}

// SyncStatus mocks base method.
func (m *MockArticleDao) SyncStatus(ctx context.Context, artId, authorId int64, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncStatus", ctx, artId, authorId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncStatus indicates an expected call of SyncStatus.
func (mr *MockArticleDaoMockRecorder) SyncStatus(ctx, artId, authorId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncStatus", reflect.TypeOf((*MockArticleDao)(nil).SyncStatus), ctx, artId, authorId, status)
}

// UpdateById mocks base method.
func (m *MockArticleDao) UpdateById(ctx context.Context, art dao.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", ctx, art)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockArticleDaoMockRecorder) UpdateById(ctx, art any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockArticleDao)(nil).UpdateById), ctx, art)
}
