test:
  key: "test"

redis:
  addr: "127.0.0.1:6379"
  password: ""

db:
  dsn: "root:root@tcp(127.0.0.1:13316)/kitbook?charset=utf8mb4&parseTime=True&loc=Local"

kafka:
  addr:
    - "localhost:9094"

etcd:
  addrs:
    - "localhost:2379"

grpc:
  server:
    etcdAddr: "localhost:2379"
    port: 8090
    bizName: "interactive"
  client:
    intr:
#      addr: "localhost:8090"
      addr: "etcd:////service/interactive"
      # 流量阈值
      threshold: 111
