// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/comment/grpc"
	"kitbook/comment/ioc"
	"kitbook/comment/repository"
	"kitbook/comment/repository/dao"
	"kitbook/comment/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	commentDao := dao.NewGormCommentDao(db)
	commentRepository := repository.NewArticleCommentRepository(commentDao)
	commentService := service.NewArticlePaymentService(commentRepository, logger)
	articleCommentServiceServer := grpc.NewArticleCommentServiceServer(commentService)
	server := ioc.InitGRpcServer(articleCommentServiceServer, logger)
	app := &App{
		rpcServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger)

var commentSvcSet = wire.NewSet(dao.NewGormCommentDao, repository.NewArticleCommentRepository, service.NewArticlePaymentService)
