// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"kitbook/interactive/grpc"
	"kitbook/interactive/repository"
	"kitbook/interactive/repository/cache"
	"kitbook/interactive/repository/dao"
	"kitbook/interactive/service"
)

// Injectors from wire.go:

func NewInteractiveServer() *grpc.InteractiveServiceServer {
	db := InitDB()
	interactiveDao := dao.NewGORMInteractiveDao(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	logger := InitLogger()
	interactiveRepository := repository.NewArticleInteractiveRepository(interactiveDao, interactiveCache, logger)
	interactiveService := service.NewArticleInteractiveService(interactiveRepository, logger)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewArticleInteractiveRepository, service.NewArticleInteractiveService)
