// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"kitbook/reward/grpc"
	"kitbook/reward/repository"
	"kitbook/reward/repository/cache"
	"kitbook/reward/repository/dao"
	"kitbook/reward/service"
)

// Injectors from wire.go:

func NewRewardServiceServer() *grpc.RewardServiceServer {
	db := InitDB()
	rewardDao := dao.NewGormRewardDao(db)
	cmdable := InitRedis()
	rewardCache := cache.NewRedisRewardCache(cmdable)
	rewardRepository := repository.NewWechatNativeRewardRepository(rewardDao, rewardCache)
	client := InitEtcd()
	paymentServiceClient := InitPaymentClient(client)
	accountServiceClient := InitAccountClient(client)
	logger := InitLogger()
	rewardService := service.NewWechatNativeRewardService(rewardRepository, paymentServiceClient, accountServiceClient, logger)
	rewardServiceServer := grpc.NewRewardServiceServer(rewardService)
	return rewardServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
	InitEtcd,
	InitPaymentClient,
	InitAccountClient,
)

var rewardSvcSet = wire.NewSet(dao.NewGormRewardDao, cache.NewRedisRewardCache, repository.NewWechatNativeRewardRepository, service.NewWechatNativeRewardService)
