// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"kitbook/internal/repository"
	"kitbook/internal/repository/cache"
	"kitbook/internal/repository/dao"
	"kitbook/internal/service"
	"kitbook/internal/web"
	"kitbook/internal/web/jwt"
	"kitbook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	limiter := ioc.InitLimiter(cmdable)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	logger := InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, limiter, jwtHandler, logger)
	db := InitDB()
	userDao := dao.NewGormUserDao(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCacheUserRepository(userDao, userCache)
	userService := service.NewNormalUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewcodeRepository(codeCache)
	smsService := ioc.InitSmsService(limiter)
	codeService := service.NewPhoneCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, jwtHandler, logger)
	wechatService := InitWechatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, jwtHandler, logger)
	articleDao := dao.NewGormArticleDao(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewCacheArticleRepository(articleDao, articleCache, userRepository)
	articleService := service.NewNormalArticleService(articleRepository, logger)
	interactiveDao := dao.NewGORMInteractiveDao(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewArticleInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewArticleInteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	engine := ioc.InitWebService(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

func NewArticleHandler(dao2 dao.ArticleDao) *web.ArticleHandler {
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	db := InitDB()
	userDao := dao.NewGormUserDao(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCacheUserRepository(userDao, userCache)
	articleRepository := repository.NewCacheArticleRepository(dao2, articleCache, userRepository)
	logger := InitLogger()
	articleService := service.NewNormalArticleService(articleRepository, logger)
	interactiveDao := dao.NewGORMInteractiveDao(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewArticleInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewArticleInteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger)
	return articleHandler
}

func NewInteractiveService() service.InteractiveService {
	db := InitDB()
	interactiveDao := dao.NewGORMInteractiveDao(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewArticleInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewArticleInteractiveService(interactiveRepository)
	return interactiveService
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, repository.NewArticleInteractiveRepository, service.NewArticleInteractiveService)

var userSvcProvider = wire.NewSet(dao.NewGormUserDao, cache.NewRedisUserCache, repository.NewCacheUserRepository, service.NewNormalUserService)
