// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"kitbook/tag/grpc"
	"kitbook/tag/ioc"
	"kitbook/tag/repository"
	"kitbook/tag/repository/cache"
	"kitbook/tag/repository/dao"
	"kitbook/tag/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	tagDao := dao.NewGormTagDao(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := repository.NewCacheTagRepository(tagDao, tagCache)
	tagService := service.NewTagService(tagRepository)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	server := ioc.InitGRpcServer(tagServiceServer, logger)
	app := &App{
		rpcServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitLogger, ioc.InitES, ioc.InitDB, ioc.InitRedis)

var tagSvcSet = wire.NewSet(dao.NewGormTagDao, cache.NewRedisTagCache, repository.NewCacheTagRepository, service.NewTagService)
