// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"kitbook/account/grpc"
	"kitbook/account/repository"
	"kitbook/account/repository/dao"
	"kitbook/account/service"
)

// Injectors from wire.go:

func NewAccountServiceServer() *grpc.AccountServiceServer {
	db := InitDB()
	accountDao := dao.NewGormAccountDao(db)
	accountRepository := repository.NewCacheAccountRepository(accountDao)
	accountService := service.NewaccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	return accountServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

var accountSvcSet = wire.NewSet(dao.NewGormAccountDao, repository.NewCacheAccountRepository, service.NewaccountService)
