// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"kitbook/comment/grpc"
	"kitbook/comment/repository"
	"kitbook/comment/repository/dao"
	"kitbook/comment/service"
)

// Injectors from wire.go:

func NewCommentServiceServer() *grpc.ArticleCommentServiceServer {
	db := InitDB()
	commentDao := dao.NewGormCommentDao(db)
	commentRepository := repository.NewArticleCommentRepository(commentDao)
	logger := InitLogger()
	commentService := service.NewArticlePaymentService(commentRepository, logger)
	articleCommentServiceServer := grpc.NewArticleCommentServiceServer(commentService)
	return articleCommentServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

var commentSvcSet = wire.NewSet(dao.NewGormCommentDao, repository.NewArticleCommentRepository, service.NewArticlePaymentService)
