// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"kitbook/search/grpc"
	"kitbook/search/repository"
	"kitbook/search/repository/dao"
	"kitbook/search/service"
)

// Injectors from wire.go:

func NewSyncServiceServer() *grpc.SyncServiceServer {
	client := InitES()
	userDao := dao.NewElasticSearchUserDao(client)
	userRepository := repository.NewUserSyncRepository(userDao)
	articleDao := dao.NewElasticSearchArticleDao(client)
	articleRepository := repository.NewArticleSyncRepository(articleDao)
	syncService := service.NewSyncService(userRepository, articleRepository)
	syncServiceServer := grpc.NewSyncServiceServer(syncService)
	return syncServiceServer
}

func NewSearchServiceServer() *grpc.SearchServiceServer {
	client := InitES()
	userDao := dao.NewElasticSearchUserDao(client)
	userRepository := repository.NewUserSyncRepository(userDao)
	articleDao := dao.NewElasticSearchArticleDao(client)
	articleRepository := repository.NewArticleSyncRepository(articleDao)
	searchService := service.NewSearchService(userRepository, articleRepository)
	searchServiceServer := grpc.NewSearchServiceServer(searchService)
	return searchServiceServer
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitLogger,
	InitES,
)

var syncSvcSet = wire.NewSet(dao.NewElasticSearchUserDao, dao.NewElasticSearchArticleDao, repository.NewArticleSyncRepository, repository.NewUserSyncRepository, service.NewSyncService)

var searchSvcSet = wire.NewSet(dao.NewElasticSearchUserDao, dao.NewElasticSearchArticleDao, repository.NewArticleSyncRepository, repository.NewUserSyncRepository, service.NewSearchService)
